print('%%writefile my_log.py')
print("import logging")
print()
print('logging.basicConfig(')
print('    filename="my.log",')
print('    level=logging.INFO,')
print('    format="%(asctime)s %(levelname)s %(message)s",')
print('    encoding="utf-8",')
print(')')
print()
print('logging.info("시작")')
print('logging.warning("주의")')
print('logging.error("오류")')
