print('%%writefile short_format.py')
print("import logging")
print()
print('logging.basicConfig(')
print('    filename="short.log",')
print('    format="%(asctime)s %(message)s",')
print('    encoding="utf-8",')
print(')')
print()
print('logging.warning("깨진 줄 건너뜀")')
